export const site = {
  url: "https://cribmarket.com",
  name: "Crib Market",
  legalName: "Crib Market",
  supportEmail: "info@cribmarket.live",
  secureBase: "https://client.cribmarket.com",
  loginUrl: "https://client.cribmarket.com/",
  registerUrl: "https://client.cribmarket.com/registration",
  demoUrl: "https://client.cribmarket.com/",
  logo: "/logo.png",
  ogImage: "/og.png",
  license: "Licensed from USA",
  licensePdf: "/Liscence.pdf",
  amlPolicyPdf: "/Roventar_Trade_AML_CFT_Policy.pdf",
  androidApkUrl: "#",
  androidApkName: "CribMarket.apk",
  chat: {
    label: "+44 7452 016572",
    href: "https://wa.me/447452016572",
  },
  address: {
    line1: "Premier Business Centre",
    line2: "10th Floor, Sterling Tower",
    line3: "14 Poudriere Street",
    city: "Port-Louis",
    country: "Mauritius",
    full: "Premier Business Centre, 10th Floor, Sterling Tower, 14 Poudriere Street, Port-Louis, Mauritius",
  },
  social: {
    facebook: "https://www.facebook.com/cribmarket/",
    telegram: "https://t.me/cribmarket",
    youtube: "https://www.youtube.com/@CribMarket",
    x: "https://x.com/CribMarket",
    instagram: "https://www.instagram.com/cribmarket/",
  },
} as const;

export const asset = {
  heroMan: "/images/hero-man.png",
  heroTradingMobile: "/images/hero-trading-mobile.png",
  trustMobile: "/images/trust-mobile.png",
  metatrader5: "/images/metatrader-5.webp",
  mt5Showcase: "/images/mt5-showcase.png",
  mt5HeroBanner: "/images/mt5-hero-banner.png",
  commoditiesHero: "/images/commodities-hero.png",
  indicesHero: "/images/indices-hero.png",
  sharesHero: "/images/shares-hero.png",
  indicesAi: "/images/indices-ai.png",
  commoditiesAi: "/images/commodities-ai.png",
  insight3: "/images/insight-3.png",
  insight4: "/images/insight-4.png",
  clock: "/images/clock.png",
  geminiAw0syn: "/images/gemini-aw0syn.png",
  geminiKgcka0: "/images/gemini-kgcka0.png",
  geminiX5dvln: "/images/gemini-x5dvln.png",
  appleIcons: "/images/apple-icons.png",
  bitcoin: "/images/bitcoin.png",
  commoditiesPic: "/images/commodities-pic.png",
  laptop: "/images/laptop.png",
  stockMarketGraph: "/images/stock-market-graph.png",
  appStoreIcon: "/images/app-store-icon.png",
  googlePlayIcon: "/images/google-play-icon.png",
  heroVideo: "/video/hero.mp4",
} as const;
